name: native_demo
description: A new Flutter project.




version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
 
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: ^1.1.0
  # cuando hay conflicto de dependeciencias y sub dependencias 
  # es mejor escribir hasta los 2 puntos ,  device_preview: 
  # y asi flutter instalara las subdependencias que necesite
  # faker genera datos ficticios
  faker: ^2.1.0
  flutter_lints: ^2.0.1
  # formatea tipo date a frases como hace un momento, hace unos dias etc
  timeago: ^3.3.0

flutter:


  uses-material-design: true

 

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf

    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
          weight: 300 
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
          weight: 400 
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 700

  # repetir proceso para nuevas fuentes
      
       
  assets: 
    - assets/images/goku.png
    - assets/emojis/angry.svg
    - assets/emojis/heart.svg
    - assets/emojis/laughing.svg
    - assets/emojis/like.svg
    - assets/emojis/sad.svg
    - assets/emojis/shocked.svg
    - assets/wallpapers/1.jpeg
    - assets/wallpapers/2.jpeg
    - assets/wallpapers/3.jpeg
    - assets/wallpapers/4.jpeg
    - assets/wallpapers/5.jpeg
    - assets/wallpapers/6.jpeg
    - assets/users/1.jpg
    - assets/users/2.jpg
    - assets/users/3.jpg
    - assets/users/4.jpg
    - assets/users/5.jpg
    - assets/users/6.jpg
    - assets/users/7.jpg
    - assets/users/8.jpg
    - assets/publications/ferrari.jpeg
    - assets/publications/flutter.jpeg
    - assets/logos/facebook.svg
